<a href="https://colab.research.google.com/github/maulik-vyas/Tensors-Fundamentals/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental Concepts about TensorFlow


In [29]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [30]:
# Create a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [31]:
# Check number of dimensions
scalar.ndim

0

In [32]:
# Create a vector
vector = tf.constant([2, 3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [33]:
# Check dimension of vector
vector.ndim

1

In [34]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [35]:
# Check dimension of matrix
matrix.ndim

2

In [36]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype="float16")
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [37]:
# number of dimensions of another_matrix
another_matrix.ndim

2

In [38]:
# Let's create a tensor
tensor = tf. constant([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [39]:
# Check the dimension
tensor.ndim

3

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

In [40]:
# Create a variable by tf.Variable
tf.Variable

tensorflow.python.ops.variables.Variable

In [41]:
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [42]:
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [43]:
# Change one of the values
changeable_tensor[1].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [45]:
unchangeable_tensor[1].assign[10]
unchangeable_tensor

AttributeError: ignored

## Creating Random Tensors

In [46]:
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [47]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [48]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of the elements in the tensor

In [49]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7],
                           [2, 4],
                           [4, 1]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 4,  1],
       [10,  7]], dtype=int32)>

In [50]:
# Scenario - 1 (Both Global and Operational Seeds are set)
tf.random.set_seed(42)
tf.random.shuffle(tf.random.uniform(shape=(3, 2)), seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

Here, as both global and operational level seeds are set, the numbers and the sequence remain the same each time you run it.

In [51]:
# Scenario - 2 (Neither of them are set)
tf.random.shuffle(tf.random.uniform(shape=(3, 2)))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.73115396, 0.89256823],
       [0.9309944 , 0.252187  ],
       [0.68789124, 0.48447883]], dtype=float32)>

When no seeds are set, it will return different values as well as sequence each time.

In [52]:
# Scenario - 3 (Global Seed set, Operational Seed not set)
tf.random.set_seed(42)
tf.random.shuffle(tf.random.uniform(shape=(3, 2)))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.03366041, 0.68467236],
       [0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255]], dtype=float32)>

The numbers and the sequence remain the same.

In [53]:
# Scenario - 4 (Global Seed not set, Operational Seed set)
tf.random.shuffle(tf.random.uniform(shape=(3, 2)), seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7413678 , 0.62854624],
       [0.01738465, 0.3431449 ],
       [0.51063764, 0.3777541 ]], dtype=float32)>

The numbers as well as the sequence change each time you run the cell.

## Other ways to create Tensors

In [54]:
one = tf.ones(shape=(10, 7))
one

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [55]:
zero = tf.zeros(shape=(10, 7))
zero

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [56]:
# Turn NumPy arrays into Tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # lowercase for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [57]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [58]:
B = tf.constant(A, shape=(3, 2, 4))
B

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from Tensors

* Shape - tensor.shape
* Rank - tensor.ndim
* Size - tf.size(tensor)
* Axis - tensor[0], tensor[:, 1]

In [59]:
# Create a rank-4 tensor
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [60]:
# Various attributes of tensor
print("Datatype of the tensor:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Number of elements of tensor:", tf.size(rank_4_tensor))
print("Number of elements of tensor:", tf.size(rank_4_tensor).numpy())

Datatype of the tensor: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Number of elements of tensor: tf.Tensor(120, shape=(), dtype=int32)
Number of elements of tensor: 120


### Indexing tensor

Tensors just can be indexed like Python Lists.

In [61]:
# Get the first 2 elements of each dimension of our rank_4_tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [62]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [63]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [64]:
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [65]:
# Get the last item of each of our rank 2 tensor
rt1 = rank_2_tensor[:, -1]
rt1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [66]:
rt1.ndim

1

In [67]:
rt2 = rank_2_tensor[:, -1:]
rt2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [4]], dtype=int32)>

In [68]:
rt2.ndim

2

In [69]:
# Add an extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [70]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [71]:
# Alternative to newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [72]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors (Tensor operations)

**Basic Operations**: `+`, `-`, `*`, `/`

**Matrix Multiplication**

In [73]:
a = tf.constant([[10, 7],
                 [3, 4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [74]:
tf.matmul(a, a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [75]:
# element-wise product
a * a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [76]:
tf.tensordot(a, a, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [77]:
# Matrix multiplication with Python @
a @ a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [78]:
# Practice
m1 = tf.constant([[1, 2, 5],
                  [7, 2, 1],
                  [3, 3, 3]])
m2 = tf.constant([[3, 5],
                  [6, 7],
                  [1, 8]])

In [79]:
m1, m2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [80]:
tf.matmul(m1, m2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [81]:
tf.tensordot(m1, m2, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [82]:
m1 @ m2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [83]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [85]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [86]:
# Transpose Y
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [87]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [88]:
# Reshape Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [89]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Matrix multiplication is also referred to as dot product. 

* `tf.matmul()`
* `tf.tensordot()`

In [90]:
# Find Positional Max and Positional Min
tf.random.set_seed(42)
M = tf.random.uniform(shape=[50])
M

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [91]:
# Find positional max
tf.argmax(M)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [92]:
M[tf.argmax(M)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [93]:
tf.reduce_max(M)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [94]:
# Find positional min
tf.argmin(M)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [95]:
M[tf.argmin(M)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [96]:
tf.reduce_min(M)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [97]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
import tensorflow as tf
scalar = tf.constant(5)
vector = tf.constant([5, 7])
matrix = tf.constant([[5, 1],
                      [9, 3]])
tensor = tf.constant([[[5, 3],
                       [1, 7]],
                      [[9, 4],
                      [6, 2]]])

In [98]:
# 2. Find the shape, rank and size of the tensors you created in 1.
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [99]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [100]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [101]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [102]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor1 = tf.random.uniform(shape=[5, 300], maxval=1)
tensor2 = tf.random.uniform(shape=[5, 300], maxval=1)

In [103]:
tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
        0.9212563 ],
       [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
        0.51477313],
       [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
        0.9892651 ],
       [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
        0.8280058 ],
       [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
        0.2584542 ]], dtype=float32)>

In [104]:
tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
        0.25082767],
       [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
        0.28176582],
       [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
        0.9987265 ],
       [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
        0.1740731 ],
       [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
        0.22565222]], dtype=float32)>

In [105]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(tensor1, tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.714005, 80.87824 , 78.32848 , 78.259705, 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.277405],
       [75.16    , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.113556, 75.401215, 72.79378 , 75.066376, 75.206535],
       [79.87284 , 83.40138 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [106]:
# 5. Multiply the two tensors you created in 3 using dot product.
tensor1 * tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.50998044, 0.30451736, 0.01618501, ..., 0.3357493 , 0.0698769 ,
        0.23107657],
       [0.0296768 , 0.05186556, 0.51247376, ..., 0.4033517 , 0.10968234,
        0.14504547],
       [0.00674238, 0.17331377, 0.11139643, ..., 0.15974203, 0.31482717,
        0.9880052 ],
       [0.01282308, 0.06803418, 0.04070826, ..., 0.51570535, 0.01522908,
        0.14413354],
       [0.3336517 , 0.18272708, 0.91464335, ..., 0.2465836 , 0.09393981,
        0.05832076]], dtype=float32)>

In [107]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor3 = tf.random.uniform(shape=[224, 224, 3], maxval=1)
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [108]:
# 7. Find the min and max values of the tensor you created in 6.
tf.reduce_max(tensor3), tf.reduce_min(tensor3)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9999902>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0967255e-05>)

In [109]:
# 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
         [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
         [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
         ...,
         [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
         [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
         [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],

        [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
         [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
         [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
         ...,
         [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
         [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
         [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],

        [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
         [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
         [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
         ...,
         [2.0133841e-01, 9.1663551e-01, 1.9890130e-01],


In [110]:
tf.squeeze(tensor4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
        [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
        [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
        ...,
        [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
        [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
        [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],

       [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
        [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
        [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
        ...,
        [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
        [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
        [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],

       [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
        [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
        [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
        ...,
        [2.0133841e-01, 9.1663551e-01, 1.9890130e-01],
        [8.0388057e-01

In [111]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor5 = tf.random.uniform(shape=[10], minval=2, maxval=40, dtype=tf.int32)
tensor5

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([19, 23, 12, 17, 24, 10,  6, 33,  8,  9], dtype=int32)>

In [112]:
tf.argmax(tensor5)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [113]:
# 10. One-hot encode the tensor you created in 9.
tf.one_hot(tensor5, depth=40)

<tf.Tensor: shape=(10, 40), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0