<a href="https://colab.research.google.com/github/maulik-vyas/Tensors-Fundamentals/blob/main/Neural%20Network%20Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

In [2]:
X = tf.constant([-7.0, -4.0, -1.0, 2.0, 5.0, 8.0, 11.0, 14.0])
y = tf.constant([3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])
X, y

(<tf.Tensor: shape=(8,), dtype=float32, numpy=array([-7., -4., -1.,  2.,  5.,  8., 11., 14.], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.], dtype=float32)>)

In [3]:
tf.random.set_seed(42)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), y, epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 833ms/step - loss: 11.5048 - mae: 11.5048
Epoch 2/5
1/1 [==============================] - 0s 19ms/step - loss: 11.3723 - mae: 11.3723
Epoch 3/5
1/1 [==============================] - 0s 9ms/step - loss: 11.2398 - mae: 11.2398
Epoch 4/5
1/1 [==============================] - 0s 20ms/step - loss: 11.1073 - mae: 11.1073
Epoch 5/5
1/1 [==============================] - 0s 9ms/step - loss: 10.9748 - mae: 10.9748


In [4]:
tf.random.set_seed(42)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 737ms/step - loss: 11.5048 - mae: 11.5048
Epoch 2/100
1/1 [==============================] - 0s 16ms/step - loss: 11.3723 - mae: 11.3723
Epoch 3/100
1/1 [==============================] - 0s 14ms/step - loss: 11.2398 - mae: 11.2398
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 11.1073 - mae: 11.1073
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 10.9748 - mae: 10.9748
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 10.8423 - mae: 10.8423
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 10.7098 - mae: 10.7098
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 10.5773 - mae: 10.5773
Epoch 9/100
1/1 [==============================] - 0s 7ms/step - loss: 10.4448 - mae: 10.4448
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 10.3123 - mae: 10.3123
Epoch 11/100
1/1 [==============================] - 0s 

In [5]:
tf.random.set_seed(42)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(lr=0.02),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), y, epochs=100)

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 11.5048 - mae: 11.5048
Epoch 2/100
1/1 [==============================] - 0s 21ms/step - loss: 11.4148 - mae: 11.4148
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 11.3248 - mae: 11.3248
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 11.2348 - mae: 11.2348
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 11.1448 - mae: 11.1448
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 11.0548 - mae: 11.0548
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 10.9648 - mae: 10.9648
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 10.8748 - mae: 10.8748
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 10.7848 - mae: 10.7848
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 10.6948 - mae: 10.6948
Epoch 11/100
1/1 [==============================] - 0s 6ms

In [6]:
tf.random.set_seed(42)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1),
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.02),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 12.3185 - mae: 12.3185
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 10.5498 - mae: 10.5498
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 9.0207 - mae: 9.0207
Epoch 4/100
1/1 [==============================] - 0s 11ms/step - loss: 7.5532 - mae: 7.5532
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 5.9801 - mae: 5.9801
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 4.2749 - mae: 4.2749
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 3.9365 - mae: 3.9365
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 4.5725 - mae: 4.5725
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 5.1528 - mae: 5.1528
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 5.4159 - mae: 5.4159
Epoch 11/100
1/1 [==============================] - 0s 10ms/step - 

In [7]:
model.predict([17.0])

1/1 [==============================] - 0s 87ms/step


array([[26.921543]], dtype=float32)

In [8]:
tf.random.set_seed(42)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.02),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), y, epochs=100)              

Epoch 1/100
1/1 [==============================] - 0s 446ms/step - loss: 13.3030 - mae: 13.3030
Epoch 2/100
1/1 [==============================] - 0s 15ms/step - loss: 8.0314 - mae: 8.0314
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 6.1540 - mae: 6.1540
Epoch 4/100
1/1 [==============================] - 0s 15ms/step - loss: 5.0304 - mae: 5.0304
Epoch 5/100
1/1 [==============================] - 0s 10ms/step - loss: 4.1413 - mae: 4.1413
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 3.7808 - mae: 3.7808
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 3.7631 - mae: 3.7631
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 3.7943 - mae: 3.7943
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 3.3434 - mae: 3.3434
Epoch 10/100
1/1 [==============================] - 0s 14ms/step - loss: 4.2072 - mae: 4.2072
Epoch 11/100
1/1 [==============================] - 0s 12ms/step - los

In [9]:
model.predict([17.0])

1/1 [==============================] - 0s 118ms/step


array([[25.340405]], dtype=float32)

In [10]:
model.predict([14.0])

1/1 [==============================] - 0s 28ms/step


array([[22.489594]], dtype=float32)