# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 12, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1df = pd.DataFrame(a1)
a2df = pd.DataFrame(a2)
a3df = pd.DataFrame(a3.reshape(3, 4))

a1df

0
0  1
1  2
2  3

In [7]:
# Create an array of shape (10, 2) with only ones
one = np.ones(shape=(10, 2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros(shape=(7, 2, 3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100, step=3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0, 10, size=(7, 2))
a5

array([[4, 8],
       [4, 8],
       [1, 7],
       [7, 5],
       [3, 6],
       [8, 0],
       [3, 5]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.random(size=(3, 5))
a6

array([[0.55647981, 0.20438123, 0.64478174, 0.64205035, 0.15744178],
       [0.06187941, 0.46506528, 0.84109813, 0.87410187, 0.44764713],
       [0.88836644, 0.43450905, 0.54851058, 0.33939867, 0.41967806]])

In [52]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.randint(0, 10, size=(4, 6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [63]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(42)
a8 = np.random.randint(1, 10, size=(3, 7))
a8
# Find the unique numbers in the array you just created
np.unique(a8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
# Find the 0'th index of the latest array you created
a8[0]

array([7, 4, 8, 5, 7, 3, 7])

In [65]:
# Get the first 2 rows of latest array you created
a8[:2]

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6]])

In [68]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2, :2]

array([[7, 4],
       [8, 5]])

In [72]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(42)
a9 = np.random.randint(0, 10, size=(3, 5))
a10 = np.ones(shape=(3, 5))
a9

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [73]:
# Add the two arrays together
a9 + a10

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [75]:
# Create another array of ones of shape (5, 3)
np.random.seed(42)
a11 = np.random.randint(0, 10, size=(5, 3))
a11

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [76]:
# Try add the array of ones and the other most recent array together
a10 + a11

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

--> Different shape.

How would you fix it?

--> Transposing one of the matrix.

In [78]:
# Create another array of ones of shape (3, 5)
np.random.seed(42)
a12 = np.ones((3, 5))
a12

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
# Subtract the new array of ones from the other most recent array
a12 - a11

ValueError: ignored

In [80]:
# Multiply the ones array with the latest array
a12 * a11

ValueError: ignored

In [81]:
# Take the latest array to the power of 2 using '**'
a11 ** 2

array([[36,  9, 49],
       [16, 36, 81],
       [ 4, 36, 49],
       [16,  9, 49],
       [49,  4, 25]])

In [82]:
# Do the same thing with np.square()
np.square(a11)

array([[36,  9, 49],
       [16, 36, 81],
       [ 4, 36, 49],
       [16,  9, 49],
       [49,  4, 25]])

In [83]:
# Find the mean of the latest array using np.mean()
np.mean(a11)

5.2

In [84]:
# Find the maximum of the latest array using np.max()
np.max(a11)

9

In [85]:
# Find the minimum of the latest array using np.min()
np.min(a11)

2

In [86]:
# Find the standard deviation of the latest array
np.std(a11)

2.039607805437114

In [87]:
# Find the variance of the latest array
np.var(a11)

4.160000000000001

In [90]:
# Reshape the latest array to (3, 5, 1)
a12.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [91]:
# Transpose the latest array
a12.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?

In [92]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(42)
a13 = np.random.randint(0, 10, size=(3, 3))
a14 = np.random.randint(0, 10, size=(3, 2))

In [93]:
a13

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]])

In [94]:
a14

array([[4, 3],
       [7, 7],
       [2, 5]])

In [95]:
# Perform a dot product on the two newest arrays you created
a13.dot(a14)

array([[59, 74],
       [76, 99],
       [64, 83]])

In [96]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a15 = np.random.randint(1, 10, size=(4, 3))
a16 = np.random.randint(1, 10, size=(4, 3))

In [97]:
a15

array([[5, 2, 8],
       [6, 2, 5],
       [1, 6, 9],
       [1, 3, 7]])

In [98]:
a16

array([[4, 9, 3],
       [5, 3, 7],
       [5, 9, 7],
       [2, 4, 9]])

In [99]:
# Perform a dot product on the two newest arrays you created
a15.dot(a16)

ValueError: ignored

It doesn't work. How would you fix it?

In [100]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a15.dot(a16.T)

array([[ 62,  87,  99,  90],
       [ 57,  71,  83,  65],
       [ 85,  86, 122, 107],
       [ 52,  63,  81,  77]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [101]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a17 = np.random.randint(0, 10, size=(2, 3))
a18 = np.random.randint(0, 10, size=(2, 3))

In [102]:
a17

array([[1, 9, 8],
       [9, 4, 1]])

In [103]:
a18

array([[3, 6, 7],
       [2, 0, 3]])

In [104]:
# Compare the two arrays with '>'
a17 > a18

array([[False,  True,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [105]:
# Compare the two arrays with '>='
a17 >= a18

array([[False,  True,  True],
       [ True,  True, False]])

In [106]:
# Find which elements of the first array are greater than 7
a17 > 7

array([[False,  True,  True],
       [ True, False, False]])

In [107]:
# Which parts of each array are equal? (try using '==')
a17 == a18

array([[False, False, False],
       [False, False, False]])

In [108]:
# Sort one of the arrays you just created in ascending order
np.sort(a17)

array([[1, 8, 9],
       [1, 4, 9]])

In [109]:
# Sort the indexes of one of the arrays you just created
np.argsort(a17)

array([[0, 2, 1],
       [2, 1, 0]])

In [113]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a17)

1

In [114]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a17)

0

In [115]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a17, axis=1)

array([1, 0])

In [116]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a17, axis=1)

array([0, 2])

In [122]:
# Create an array of normally distributed random numbers
a19 = np.random.normal(size=(3, 3))
a19

array([[-1.39341694, -2.17833425, -1.04389641],
       [ 0.17269371,  0.32419877,  0.74585954],
       [-1.83658324,  0.56446424,  0.02550067]])

In [117]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a20 = np.arange(1, 100, step=10)
a20

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.