<a href="https://colab.research.google.com/github/maulik-vyas/Tensors-Fundamentals/blob/main/tf-basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
matrix = tf.constant([[[1, 2, 4, 5],
                       [2, 3, 5, 7]],
                      [[4, 6, 4, 2],
                       [9, 4, 3, 6]],
                      [[6, 4, 6, 3],
                      [4, 6, 3,7]]])

matrix

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 2, 4, 5],
        [2, 3, 5, 7]],

       [[4, 6, 4, 2],
        [9, 4, 3, 6]],

       [[6, 4, 6, 3],
        [4, 6, 3, 7]]], dtype=int32)>

In [4]:
matrix.ndim

3

In [5]:
scalar.shape

TensorShape([])

In [6]:
matrix.shape

TensorShape([3, 2, 4])

In [7]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [8]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4]])

not_shuffled

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [9]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7]], dtype=int32)>

In [10]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print("f:", f())  # prints '(A1, A2)'
print("g:", g())  # prints '(A1, A2)'

f: (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
g: (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [11]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [12]:
a = tf.constant([[12, 34],
                 [76, 21]])

In [13]:
tf.random.shuffle(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[76, 21],
       [12, 34]], dtype=int32)>

In [14]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.3253647], shape=(1,), dtype=float32)
tf.Tensor([0.59750986], shape=(1,), dtype=float32)


In [15]:
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.9099175], shape=(1,), dtype=float32)
tf.Tensor([0.00412071], shape=(1,), dtype=float32)


In [16]:
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.3780992], shape=(1,), dtype=float32)
tf.Tensor([0.6765541], shape=(1,), dtype=float32)


In [17]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [18]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [19]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [20]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [21]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [22]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.4243431], shape=(1,), dtype=float32)
tf.Tensor([0.92531705], shape=(1,), dtype=float32)


In [23]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.69941723], shape=(1,), dtype=float32)
tf.Tensor([0.7062043], shape=(1,), dtype=float32)


In [24]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.33758223], shape=(1,), dtype=float32)
tf.Tensor([0.03662574], shape=(1,), dtype=float32)


In [25]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [26]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print("foo1:", foo())  # prints '(A1, A1)'
print("foo2:", foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print("bar1:", bar())  # prints '(A1, A2)'
print("bar2:", bar())  # prints '(A3, A4)'

foo1: (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
foo2: (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
bar1: (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
bar2: (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


In [27]:
t1 = tf.constant([[[10, 34],
                   [54, 62]],
                  [[95, 21],
                   [56, 33]],
                  [[11, 59],
                   [82, 48]]])

t1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 34],
        [54, 62]],

       [[95, 21],
        [56, 33]],

       [[11, 59],
        [82, 48]]], dtype=int32)>

In [28]:
tf.random.shuffle(t1)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[11, 59],
        [82, 48]],

       [[10, 34],
        [54, 62]],

       [[95, 21],
        [56, 33]]], dtype=int32)>

In [29]:
tf.random.shuffle(t1)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[95, 21],
        [56, 33]],

       [[11, 59],
        [82, 48]],

       [[10, 34],
        [54, 62]]], dtype=int32)>

In [30]:
t2 = tf.constant([[12, 44],
                  [34, 56],
                  [88, 11]])
t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 44],
       [34, 56],
       [88, 11]], dtype=int32)>

In [31]:
tf.random.set_seed(42)
tf.random.shuffle(t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[34, 56],
       [88, 11],
       [12, 44]], dtype=int32)>

In [32]:
tf.random.set_seed(42)
tf.random.shuffle(t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[34, 56],
       [88, 11],
       [12, 44]], dtype=int32)>

In [33]:
tf.random.set_seed(42)
tf.random.shuffle(t2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 44],
       [34, 56],
       [88, 11]], dtype=int32)>

In [34]:
tf.random.set_seed(42)
tf.random.shuffle(t2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 44],
       [34, 56],
       [88, 11]], dtype=int32)>

In [35]:
tf.random.shuffle(t2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[88, 11],
       [12, 44],
       [34, 56]], dtype=int32)>

In [36]:
tf.random.shuffle(t2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[88, 11],
       [12, 44],
       [34, 56]], dtype=int32)>

In [37]:
tf.random.shuffle(t2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[34, 56],
       [88, 11],
       [12, 44]], dtype=int32)>

In [38]:
tf.random.shuffle(t2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[34, 56],
       [88, 11],
       [12, 44]], dtype=int32)>

In [39]:
import numpy as np

numpy_A = np.arange(1, 25, dtype='int32')
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [40]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [41]:
B = tf.constant(numpy_A, shape=(2, 3, 4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [42]:
C = tf.constant(numpy_A, shape=(3,1,8))
C

<tf.Tensor: shape=(3, 1, 8), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7,  8]],

       [[ 9, 10, 11, 12, 13, 14, 15, 16]],

       [[17, 18, 19, 20, 21, 22, 23, 24]]], dtype=int32)>

In [43]:
rank_2_tensor = tf.constant([[3, 4],
                             [10, 7]])

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7]], dtype=int32)>

In [44]:
rank_2_tensor.ndim

2

In [45]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>

In [46]:
tensor = tf.constant([[10, 7],
                      [3, 4]])

In [47]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [49]:
tf.multiply(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [50]:
tensor_A = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
tensor_B = tf.constant([[3,5],
                        [6,7],
                        [1,8]])
tensor_A, tensor_B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [51]:
tf.matmul(tensor_A, tensor_B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [52]:
tensor_A @ tensor_B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [53]:
tensor_C = tf.constant([[1,2,4],
                        [4,5,6]])
tensor_C

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [4, 5, 6]], dtype=int32)>

In [54]:
tf.matmul(tensor_A, tf.transpose(tensor_C))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25, 44],
       [15, 44],
       [21, 45]], dtype=int32)>

In [55]:
tensor1 = tf.constant([[12, 34],
                       [22, 44]])
tensor1.dtype

tf.int32

In [56]:
tensor2 = tf.constant([[11.5, 6.9],
                       [33.5, 99.1]])
tensor2.dtype

tf.float32

In [57]:
tf.cast(tensor1, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[12., 34.],
       [22., 44.]], dtype=float16)>

In [58]:
tensor_A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [59]:
tensorD = tf.constant([[12, 45, 63],
                       [37, 67, 35],
                       [49, 81, 4]])

tensorD

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 45, 63],
       [37, 67, 35],
       [49, 81,  4]], dtype=int32)>

In [60]:
tensorE = tf.constant([[14, 56, 73],
                       [30, 21, 62],
                       [91, 4, 82]])
tensorE

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 56, 73],
       [30, 21, 62],
       [91,  4, 82]], dtype=int32)>

In [61]:
tf.math.minimum(tensorD, tensorE)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 45, 63],
       [30, 21, 35],
       [49,  4,  4]], dtype=int32)>

In [62]:
tf.math.maximum(tensorD, tensorE)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 56, 73],
       [37, 67, 62],
       [91, 81, 82]], dtype=int32)>

In [63]:
tf.math.add(tensorD, tensorE)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 26, 101, 136],
       [ 67,  88,  97],
       [140,  85,  86]], dtype=int32)>

In [64]:
tf.math.reduce_mean(tensorD)

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [65]:
tf.math.minimum(tensorD, tensorE)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 45, 63],
       [30, 21, 35],
       [49,  4,  4]], dtype=int32)>

In [66]:
tf.reduce_min(tensorD)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [67]:
tf.reduce_sum(tensorD)

<tf.Tensor: shape=(), dtype=int32, numpy=393>

In [68]:
import numpy as np

F = tf.constant(np.random.uniform(1, 100, 50), dtype='float16')
F

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([52.94 , 72.2  , 60.44 , 58.9  , 73.75 , 55.4  , 43.5  , 11.8  ,
       99.44 , 65.5  , 44.2  , 68.94 , 66.25 , 19.22 , 16.78 , 21.62 ,
       67.1  , 77.6  , 20.8  , 80.6  , 83.44 , 59.9  , 32.44 , 50.6  ,
       19.28 ,  4.39 , 35.22 , 47.44 , 16.8  , 59.94 ,  2.494,  7.535,
       24.66 , 38.66 , 93.5  , 29.08 , 55.66 , 48.8  , 80.8  ,  8.59 ,
       27.52 , 38.84 , 86.4  , 26.23 , 27.28 , 57.34 , 29.28 , 26.89 ,
       83.56 , 77.44 ], dtype=float16)>

In [69]:
tf.math.reduce_variance(F)

<tf.Tensor: shape=(), dtype=float16, numpy=663.5>

In [70]:
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float16, numpy=25.77>

In [71]:
import tensorflow_probability as tfp

tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=float16, numpy=663.5>

In [72]:
tfp.stats.stddev(F)

<tf.Tensor: shape=(), dtype=float16, numpy=25.77>

In [73]:
tf.math.reduce_variance(tf.cast(tensorD, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=559.7778>

In [74]:
E = tf.constant(np.random.randint(1, 100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94, 33, 44, 37, 37, 26, 31, 15, 53, 36, 72, 23, 29, 32, 73,  6, 42,
       32, 92, 26, 54, 55, 11, 68, 65,  7, 33,  9, 81, 89,  4,  6, 41, 55,
       62, 55, 52,  1, 18, 94, 75, 90, 65, 46, 51,  5, 64, 99, 65, 67])>

In [75]:
tf.math.reduce_variance(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=743.92>

In [76]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=744>

In [77]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=743.92>

In [78]:
tf.random.set_seed(42)
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [79]:
tf.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [80]:
tf.random.set_seed(42)
I = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
I

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [81]:
I_squeezed = tf.squeeze(I)
I_squeezed.shape

TensorShape([50])

In [82]:
I_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [83]:
some_list = [0, 1, 2]
tf.one_hot(some_list, depth=6)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)>

In [84]:
J = tf.range(1, 10)
J

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [85]:
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [86]:
tf.sqrt(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [87]:
tf.math.log(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [88]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]